### PR TITLE
feat: add new attribute candidate users for assignment

### LINKED ISSUE #37: I can set candidate users on a user task for Camunda Platform 8
__Is your feature request related to a problem? Please describe__
I want to be able to define the candidateUsers attributes of the assignment definition of a user task from the camunda-modeler.

Child of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/774

### PR DESCRIPTION
**Pull request by lzgabel**
related to camunda/camunda-modeler#3151

closes #37

### CODE REVIEW

**Comment by barmac** [comment]
This requires https://github.com/camunda/zeebe/pull/10459 to be merged and scheduled for release.

**Comment by lzgabel** [comment]
Hi @barmac. camunda/zeebe#10459 version `8.2.0-alpha1` has been released. Is there a schedule for this task?

**Comment by barmac** [comment]
Cool, so we are able to test this. I assigned reviewers as I can't look into this right now.

**Review by philippfromme — APPROVED** [review]
Looks good! 💅🏻 

Thank you for your contribution! 🥇

**Pull request merged**
